name: 'Release: Publish to NuGet'

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  createArtifacts:
    name: Generate NuGet Packages
    runs-on: ubuntu-latest
    env: 
      PROJECT_PATH: './src/Simbrella.Infrastructure.Time/Simbrella.Infrastructure.Time.csproj'

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore
        working-directory: src
      
      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: src
        
      - name: Create Release Artifact
        run: dotnet pack ${{ env.PROJECT_PATH }} -c Release --no-build --include-symbols -o ./artifacts/release

      - name: 'Save release artifact'
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./artifacts/release/*  

  publishRelease:
    name: Publish Release NuGet Package
    environment: release
    needs: createArtifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: release
          
      - name: Publish NuGet Package
        run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
